import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React from "react";
import {
  Platform,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

type Section = {
  title: string;
  body: string[];
};

const SECTIONS: Section[] = [
  {
    title: "1. Information We Collect",
    body: [
      "We collect the details you provide directly, such as your name, email, phone number, and profile photo, along with information generated by using the app, like booking history and chat messages with technicians.",
    ],
  },
  {
    title: "2. Location Data",
    body: [
      "Your default service address, and the coordinates behind it, are stored so we can match you with nearby technicians and let them navigate to you. You control this in Settings › Location, and you decide whether to share your precise device location or enter an address manually.",
    ],
  },
  {
    title: "3. Payment Information",
    body: [
      "When you save a payment method, card details are tokenized and processed by our payment partners — ITKonek doesn't store your full card number. We keep only what's needed to display your saved method, such as the last 4 digits.",
    ],
  },
  {
    title: "4. How We Use Your Information",
    body: [
      "We use your information to schedule and dispatch repairs, process payments, send booking and billing updates, and improve the reliability of the service. We don't sell your personal information.",
    ],
  },
  {
    title: "5. Sharing With Technicians",
    body: [
      "When you book a repair, the assigned technician can see the details needed to complete the job — your name, contact number, and service address. Technicians don't have access to your payment details or account credentials.",
    ],
  },
  {
    title: "6. Data Security",
    body: [
      "We use industry-standard safeguards to protect your data in transit and at rest. No system is perfectly secure, so we also encourage strong, unique passwords and keeping your app up to date.",
    ],
  },
  {
    title: "7. Data Retention",
    body: [
      "We keep account and booking information for as long as your account is active, and for a limited period afterward where needed for legal, tax, or dispute-resolution purposes.",
    ],
  },
  {
    title: "8. Your Choices",
    body: [
      "You can review and update your personal information, location, and notification preferences anytime from Settings. You may also request deletion of your account by contacting support.",
    ],
  },
  {
    title: "9. Changes to This Policy",
    body: [
      "If we make material changes to how we handle your data, we'll notify you in the app before the change takes effect.",
    ],
  },
  {
    title: "10. Contact Us",
    body: [
      "For privacy questions or requests, reach out through the Help section in Settings, or send feedback directly from the app.",
    ],
  },
];

export default function PrivacyScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar
        barStyle="dark-content"
        backgroundColor="#F9FAFB"
        translucent={false}
      />
      <View style={styles.header}>
        <TouchableOpacity
          onPress={() => router.push("/(customer)/(tabs)/settings")}
          style={styles.backButton}
          hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
        >
          <Ionicons name="chevron-back" size={22} color="#111827" />
        </TouchableOpacity>
        <Text style={styles.title}>Privacy Policy</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.updatedText}>Last updated: July 2026</Text>
        <Text style={styles.intro}>
          This policy explains what information ITKonek collects, how it's used,
          and the choices you have.
        </Text>

        {SECTIONS.map((section) => (
          <View key={section.title} style={styles.section}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            {section.body.map((paragraph, idx) => (
              <Text key={idx} style={styles.paragraph}>
                {paragraph}
              </Text>
            ))}
          </View>
        ))}

        <View style={styles.footerSpacer} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight || 0 : 0,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 8,
  },
  backButton: { padding: 8 },
  title: { fontSize: 17, fontWeight: "800", color: "#111827" },
  content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 24 },
  updatedText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#9CA3AF",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  intro: {
    fontSize: 13,
    color: "#6B7280",
    lineHeight: 19,
    marginBottom: 24,
  },
  section: {
    marginBottom: 22,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 6,
  },
  paragraph: {
    fontSize: 13,
    color: "#374151",
    lineHeight: 20,
    marginBottom: 6,
  },
  footerSpacer: { height: 20 },
});
